Updated requirements.in
ansible-community/toolset pull request #85
Opened 2021-01-26 20:52 UTC by dingus9

fixes error where molecule-openstack requires openstacksdk

This error only appears when using molecule-openstack as the driver

2021-01-26 20:57 UTC, tadeboro commented
@dingus9 You will also need to update the requirements.txt because that file is tracked in repo. Use pip-compile to generate the file.

2021-01-26 23:07 UTC, dingus9 commented
> @dingus9 You will also need to update the requirements.txt because that file is tracked in repo. Use pip-compile to generate the file.

I assumed that would be part of the the pipeline ;)

2021-01-26 23:43 UTC, dingus9 commented
Hey not exactly sure why it says git is in a dirty status... can you point me in the right direction

2021-01-27 00:17 UTC, tadeboro requested changes

2021-01-27 00:17 UTC, tadeboro commented on requirements.txt
> +#    pip-compile --allow-unsafe --no-annotate --output-file=requirements2.txt requirements.in
This line should not be changed because instructions did not change. This is what is triggering the CI.

2021-01-27 09:58 UTC, ssbarnea commented
@dingus9 Rebase and run tox locally before uploading. If tox is passing locally it will also pass on CI.

2021-01-27 15:38 UTC, dingus9 commented
> @dingus9 Rebase and run tox locally before uploading. If tox is passing locally it will also pass on CI.

why does tox dirty my commit? WTF

2021-01-27 15:44 UTC, ssbarnea commented
That is because you did not run it locally, the linter job does regenerate the requirements and finishes with dirty-status failure if the regenerated file is different than the one in the commit. That assures we do not merge manually modified files.

2021-01-27 15:54 UTC, dingus9 commented
ugh I'm running tox locally tox is passing, did a merge to origin main... IDK what you guys are doing, why isn't the requirements.txt just an output of a pipeline stage? I'm just going to close it's wasting everyones time.

2021-01-27 15:54 UTC, closed without merging

2021-01-27 16:05 UTC, ssbarnea commented
@dingus9 Yeah, is not your fault. I am working on it, it needs some extra changes to the pipeline because the result of the pip-compile depends on python/platform being used, this being the root cause.  I hope i get it to work by pinning python version.